### ISSUE TITLE
Formulierung bei A9 in comprehensions and dictionaries

### ISSUE THREAD

**Issue by lillyayu** [Benkex/Lerngruppenaktion#2]
Hi, ich wollte nur vorschlagen die Aufgabe A9 zu dictionary comprehension umzuformulieren. 
Mir war nicht klar, dass der key ein string aus 4 mal dem gleichen character sein soll (bsp: "ffff"), ich dachte der string sollte 4 characters lang sein und dabei soll jeder dieser characters zufällig ausgewählt sein (bsp: "kGfj"). Man könnte zum Beispiel nach "der zufällige strings der Länge 4 als keys" noch ein Beipsiel für einen key einfügen. 
Vielen vielen Dank auf jeden fall, dass du dir die Mühe gemacht hast, die Aufgaben sind echt super hilfreich, besonders wenn man vor dem Studium noch keine Programmier Erfahrung hat.
LG Lilly

**Comment by Benkex** [comment]
Hey Lilly, danke für Deine Anmerkung, die Formulierung ist tatsächlich ungenau,  
ich habe gerade Beispiele hinzugefügt, wie Du vorgeschlagen hast:)  
Ich freue mich, dass Dir die Aufgaben hilfreich waren:)  
Falls Du weitere Anmerkungen oder Ideen hast, gerne hier im Issues posten, wie eben.  
Ich hab's nie gedacht, dass es mal benutzt wird:D

**Comment by lillyayu** [comment]
ich mache überall fleißig Werbung für die Aufgaben, es sind schon bestimmt mindestens 15 Leute die jetzt die Aufgaben machen. Es ist echt cool von dir, dass du dir die Mühe gemacht hast sie zu erstellen!

**Comment by Benkex** [comment]
Super, vielen Dank!:)) Das freut mich echt... Mach das bitte weiter:)
Wenn Du Leute begegnest, die Programmiererfahrung / Lust haben, kannst Du auch gerne empfehlen, im Projekt mitzuarbeiten, es gibt nichts schöneres als Zusammenarbeit.
Der Repo ist bisher auch von mehreren Leuten zusammengestellt worden: [Bitzi](https://github.com/FaBitzen), [Juls](https://github.com/Julez37) und ich, bzw. die Leute, die ihre Lösungen uns geschickt haben, wie Raymond oder Leo.
